"""add order status

Revision ID: 66b70ecf1082
Revises: c11b80acc8e2
Create Date: 2026-09-29 22:17:24.724950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b70ecf1082'
down_revision: Union[str, Sequence[str], None] = 'c11b80acc8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'orders',
    sa.Column(
        'status',
        sa.String(length=50),
        nullable=False,
        server_default='pending'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
